# Generated by Django 5.1.5 on 2025-10-21 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_agent', '0003_seodata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SEOData',
        ),
    ]
